"""Allow null values

Revision ID: 9fa7edbf0d9e
Revises: 96f93a88a9c1
Create Date: 2023-04-28 17:47:37.198564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa7edbf0d9e'
down_revision = '96f93a88a9c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.alter_column('recipient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('message_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.alter_column('message_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('recipient_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
